# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab5f59a58cb0db16c0abef9ee5c633c10cd6057a213cab3d172f28813b401dba71533ce84aa035c58f5a665a5ff3c7ba4cdc9f8f44a02cd0b420fdf8e2cb4481

test:
  secret_key_base: 195e4d141940962059e6d393431e078cfafbcc5a75c19099be351dcb7da73a8cccc7f378d92330f3aa55fdd2aea31425ba1f5154a4a1ca88fa8ad47e960ae86f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
